-- MySQL Script generated by MySQL Workbench
-- Fri Feb  6 15:06:56 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ритуальные_услуги
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ритуальные_услуги` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `ритуальные_услуги` ;

-- -----------------------------------------------------
-- Table `ритуальные_услуги`.`пользователи`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ритуальные_услуги`.`пользователи` (
  `id_пользователя` INT NOT NULL AUTO_INCREMENT,
  `имя` VARCHAR(50) NOT NULL,
  `фамилия` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `пароль` VARCHAR(255) NOT NULL,
  `телефон` VARCHAR(20) NULL DEFAULT NULL,
  `дата_создания` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_пользователя`),
  UNIQUE INDEX `email` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ритуальные_услуги`.`заказы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ритуальные_услуги`.`заказы` (
  `id_заказа` INT NOT NULL AUTO_INCREMENT,
  `id_пользователя` INT NULL DEFAULT NULL,
  `дата_заказа` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `статус` ENUM('в_обработке', 'оплачен', 'отправлен', 'выполнен', 'офлайн') NULL DEFAULT 'в_обработке',
  `общая_сумма` DECIMAL(10,2) NULL DEFAULT NULL,
  `способ_оплаты` ENUM('онлайн', 'офлайн') NULL DEFAULT 'онлайн',
  PRIMARY KEY (`id_заказа`),
  INDEX `id_пользователя` (`id_пользователя` ASC) ,
  CONSTRAINT `заказы_ibfk_1`
    FOREIGN KEY (`id_пользователя`)
    REFERENCES `ритуальные_услуги`.`пользователи` (`id_пользователя`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ритуальные_услуги`.`категории_товаров`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ритуальные_услуги`.`категории_товаров` (
  `id_категории` INT NOT NULL AUTO_INCREMENT,
  `название` VARCHAR(50) NOT NULL,
  `описание` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_категории`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ритуальные_услуги`.`товары`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ритуальные_услуги`.`товары` (
  `id_товара` INT NOT NULL AUTO_INCREMENT,
  `название` VARCHAR(100) NOT NULL,
  `описание` TEXT NULL DEFAULT NULL,
  `цена` DECIMAL(10,2) NOT NULL,
  `количество_на_складе` INT NULL DEFAULT '0',
  `id_категории` INT NULL DEFAULT NULL,
  `оплата_онлайн` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`id_товара`),
  INDEX `id_категории` (`id_категории` ASC) ,
  CONSTRAINT `товары_ibfk_1`
    FOREIGN KEY (`id_категории`)
    REFERENCES `ритуальные_услуги`.`категории_товаров` (`id_категории`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ритуальные_услуги`.`товары_в_заказе`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ритуальные_услуги`.`товары_в_заказе` (
  `id_товара_в_заказе` INT NOT NULL AUTO_INCREMENT,
  `id_заказа` INT NULL DEFAULT NULL,
  `id_товара` INT NULL DEFAULT NULL,
  `количество` INT NOT NULL,
  `цена_на_момент_покупки` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_товара_в_заказе`),
  INDEX `id_заказа` (`id_заказа` ASC) ,
  INDEX `id_товара` (`id_товара` ASC) ,
  CONSTRAINT `товары_в_заказе_ibfk_1`
    FOREIGN KEY (`id_заказа`)
    REFERENCES `ритуальные_услуги`.`заказы` (`id_заказа`),
  CONSTRAINT `товары_в_заказе_ibfk_2`
    FOREIGN KEY (`id_товара`)
    REFERENCES `ритуальные_услуги`.`товары` (`id_товара`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
